Packaging experiment file
MEDomics-UdeS/MEDomicsLab pull request #105
Opened 2023-10-19 20:32 UTC by Blain354

2023-10-20 16:26 UTC, Sari27 requested changes

2023-10-20 16:26 UTC, Sari27 commented on renderer/components/layout/sidebarTools/flowSceneSidebar.jsx
> +  const createSceneContent = (path, sceneName, extension) => {
docstring

2023-10-20 16:26 UTC, Sari27 commented on renderer/components/layout/sidebarTools/flowSceneSidebar.jsx
> +  // }, [dbSelectedItem])
code commenté

2023-10-20 16:26 UTC, Sari27 commented on renderer/components/learning/workflow.jsx
import Button ligne 32 non utilisé

2023-10-20 16:26 UTC, Sari27 commented on renderer/utilities/customZipFile.js
> +export const customZipFile2Object = async (path) => {
docstring

2023-10-20 16:26 UTC, Sari27 commented on renderer/utilities/customZipFile.js
> +  async toObject() {
docstring

2023-10-20 16:26 UTC, Sari27 commented on renderer/utilities/customZipFile.js
> +  openContentToObject(folderPath) {
docstring

2023-10-20 16:26 UTC, Sari27 commented on renderer/utilities/customZipFile.js
> +  static getPathType(path) {
docstring

2023-10-23 02:29 UTC, Blain354 commented on flask_server/learning/MEDml/MEDexperiment_learning.py
> +                return pycaret_exp.load_experiment(saved_path, data=data)
oui son seul référencement est juste a coté, pas besoin que ce soit accessible globalement

2023-10-23 02:30 UTC, Blain354 commented on flask_server/learning/MEDml/nodes/Analyze.py
> +                    os.rename(return_path, new_path)
oui son seul référencement est juste a coté, pas besoin que ce soit accessible globalement

2023-10-23 02:34 UTC, Blain354 commented on medomics.dev.js
> +  runServerAutomatically: false,
ouais mais faudrait l'ajouter manuellement lorsqu'on git clone... comme le fichier conda

2023-10-23 13:50 UTC, merged