Develop guillaume
MEDomics-UdeS/MEDomicsLab pull request #4
Opened 2023-09-05 20:00 UTC by Blain354

2023-09-05 20:13 UTC, mvallieres commented
Much better when it is asked to be merged into the develop branch, and not main ;)

2023-09-06 20:38 UTC, Sari27 requested changes
Super travail, surtout au niveau des fichiers .jsx qui sont pour la plupart bien commentés ! Ce serait super de faire de même avec les fichiers .py. Il y a quelque petites choses à corriger, surtout pour la partie qui cause une erreur dans le fonctionnement de l'application.

2023-09-06 20:38 UTC, Sari27 commented on Flask_server/learning/MEDml/MEDexperiment.py
>  # from pycaret.survival_analysis.oop import SurvivalAnalysisExperiment
Il faudrait enlever les lignes de codes commentées (dans tout le fichier) et les imports non utilisés 
Ce commentaire est à prendre en compte sur tous les fichiers modifiés, surtout les .py

2023-09-06 20:38 UTC, Sari27 commented on Flask_server/learning/MEDml/MEDexperiment.py
> +def isPrimitive2(obj):
Pourquoi avoir 2 fonctions isPrimitive ?

2023-09-06 20:38 UTC, Sari27 commented on renderer/components/flow/flowPageBase.jsx
> +  const { pageInfos } = useContext(PageInfosContext)
Lorsque l'on essaye d'ouvrir le Extraction module dans l'application cette ligne cause une erreur
![bug_extraction](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/48992399/f242f3f9-1d65-476d-80d6-1e1ee77c6625)

2023-09-07 16:17 UTC, Sari27 requested changes
Erreur avec le coda environment au lancement de l'application

2023-09-07 16:17 UTC, Sari27 commented on main/background.js
> +  //**** PRODUCTION ****//
Le bloc commenté est vraiment nécessaire ?

2023-09-08 13:49 UTC, Sari27 approved these changes

2023-09-08 13:50 UTC, merged