Dev extraction
MEDomics-UdeS/MEDomicsLab pull request #61
Opened 2023-09-18 17:59 UTC by Blain354

2023-09-19 14:33 UTC, Sari27 requested changes
Super travail, belle documentation, mais il reste des petites choses à régler avant de pouvoir merge

2023-09-19 14:33 UTC, Sari27 commented on flask_server/server.py
Je ne sais pas si c'est lié spécifiquement à ce fichier mais il est impossible d'uploader des fichiers dans l'input de extraction_image, ça cause de erreurs NETWORK
![extraction2](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/48992399/55225db3-ba4c-47da-ab5b-22b831bfb440)

2023-09-19 14:33 UTC, Sari27 commented on renderer/components/extraction/flowCanvas.jsx
Il reste le import de ResultButton à enlever ligne 25 (non utilisé)
Ligne 53  `const [results, setResults] = useState({}) // results is used to store radiomic features results` à enlever

2023-09-19 14:33 UTC, Sari27 commented on test/extraction/IBSI/Phase2E_settings.json
Ce dossier test est-il nécessaire ?

2023-09-19 18:23 UTC, AndreanneAllaire commented on test/extraction/IBSI/Phase2E_settings.json
Oui, ce sont les settings utilisés pour les tests IBSI. Il faudra probablement ajouter les autres fichiers de settings plus tard.

2023-09-19 18:25 UTC, AndreanneAllaire commented on renderer/components/extraction/flowCanvas.jsx
Il n'est pas utilisé mais c'était prévu de l'utiliser pour afficher tous les résultats au lieu des résultats par noeud. Je l'avais conservé pour permettre au prochain dev de bien voir où mettre les résultats.

2023-09-20 18:10 UTC, Sari27 approved these changes

2023-09-20 18:11 UTC, merged