Merge before pr blain and nico
MEDomics-UdeS/MEDomicsLab pull request #71
Opened 2023-09-25 14:00 UTC by NicoLongfield

Added the sidebar layers
Fixed display issues for the learning module when resizing and toggling the node menu.

2023-09-25 19:41 UTC, Sari27 requested changes
Beau travail mais encore de la mise en forme / commentaires à faire avant le merge

2023-09-25 19:41 UTC, Sari27 commented on flask_server/learning/MEDml/MEDexperiment.py
> -        tmp_dir = self.global_json_config['saving_path']
Pourquoi avoir à nouveau enlevé le self.global_json_config ligne 72 ?

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/layout/iconSidebar.jsx
> +import { Files, HouseFill, Gear, GraphUp, Image, Magnet, Server, Stack, TextLeft, FileEarmarkBarGraph, RocketTakeoff, PatchCheck, Search, BandaidFill, Send, Diagram3Fill, Clipboard2Data, ClipboardChe
Enlever tous les imports non utilisés ligne 2

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/layout/layoutContext.jsx
> +import LearningPage from "../mainPages/learning"
import non utilisé ligne 2

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/layout/sidebarTools/learningSidebar.jsx
Imports non utilisés et manque de docstring dans ce fichier

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/layout/sidebarTools/sidebarDirectoryTreeControlled.jsx
> +  const { dispatchAction } = useContext(ActionContext) // We get the dispatchAction function from the context to dispatch actions to the action reducer
import non utilisé

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/learning/workflow.jsx
import non utilisé ligne 15

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/mainPages/layoutTest.jsx
imports et variables non utilisées -> ce fichier sert-il encore ?

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/mainPages/moduleBasics/modulePage.jsx
Import non utilisé ligne 5

2023-09-25 19:41 UTC, Sari27 commented on renderer/components/workspace/medDataObject.js
Il y a deux fois la fonction createFolder dans ce fichier + import non utilisé ligne 3

2023-09-25 19:41 UTC, Sari27 commented on renderer/styles/flow/reactFlow.css
> +.flow-btn-panel-top .center {
définition vide ?

2023-09-25 19:41 UTC, Sari27 commented on renderer/styles/learning/learning.css
Beaucoup de code commenté dans ce fichier

2023-09-25 19:41 UTC, Sari27 commented on renderer/styles/sidebarTree.css
> +.medomics-layer:hover {
définition vide

2023-09-25 19:41 UTC, Sari27 commented on renderer/styles/sidebarTree.css
Beaucoup de code commenté dans ce fichier

2023-09-25 19:41 UTC, Sari27 commented on renderer/styles/test.module.css
Code commenté

2023-09-25 20:07 UTC, Blain354 commented on renderer/components/mainPages/layoutTest.jsx
Nico travaille en ce moment à convertir/remplacer ce fichier. C'est pas un pr en lien avec les modifs de layout sur quoi il travaille alors on laisse ca et pour son prochain pr tu lui demandera si c'est utile

2023-09-26 12:30 UTC, Blain354 commented on renderer/components/mainPages/moduleBasics/modulePage.jsx
![image](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/54538310/ac4e19fc-8f05-409e-9742-93a4e8a4f930)

2023-09-26 12:31 UTC, Blain354 commented on renderer/components/mainPages/moduleBasics/modulePage.jsx
ca ne me dit pas qu'il n'est pas utilisé

2023-09-26 12:31 UTC, Blain354 commented on renderer/components/learning/workflow.jsx
![image](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/54538310/74bb30f7-03bc-4128-927a-eeeadfe5c1e7)

2023-09-26 12:32 UTC, Blain354 commented on renderer/components/learning/workflow.jsx
meme chose ici

2023-09-26 13:07 UTC, Sari27 approved these changes
Nice job !

2023-09-26 13:07 UTC, merged