97 refactoring medexperiment code cleaning and modular
MEDomics-UdeS/MEDomicsLab pull request #99
Opened 2023-10-17 13:28 UTC by Blain354

2023-10-17 19:35 UTC, Sari27 requested changes

2023-10-17 19:35 UTC, Sari27 commented on flask_server/learning/MEDml/MEDexperiment.py
Imports ClassificationExperiment et RegressionExperiment à enlever

2023-10-17 19:35 UTC, Sari27 commented on flask_server/learning/MEDml/MEDexperiment_learning.py
Des docstring pour la classe et ses fonctions seraient nice

2023-10-17 19:35 UTC, Sari27 commented on flask_server/learning/app_learning_blueprint.py
imports non utilisés

2023-10-17 19:35 UTC, Sari27 commented on flask_server/requirements.txt
> +tsdownsample==0.1.2
ligne en double

2023-10-17 19:35 UTC, Sari27 commented on flask_server/server.py
imports non utilisés

2023-10-17 19:35 UTC, Sari27 commented on renderer/pages/_app.js
> +  // }, [])
Code commenté

2023-10-17 19:35 UTC, Sari27 commented on renderer/styles/globals.css
Pourquoi avoir mit le css de la progressBar dans global alors que la progressBar est dans flow ? Si tu veux que la progressBar soit disponible dans tous les composants le plus logique selon moi est de la mettre directement dans le dossier components

2023-10-18 11:50 UTC, Blain354 commented on flask_server/learning/MEDml/MEDexperiment_learning.py
étant une classe qui hérite de MEDexperiment, quand tu hover sur les fonctions abstraites, tu as la doc configuré par MEDexperiment.py

2023-10-18 12:00 UTC, Blain354 commented on renderer/pages/_app.js
> +  // }, [])
ce code clear la mémoire de l'application lorsque celle ci load. dans mon cas, c'est plus rapide niveau développement quand ca load la derniere affaire, mais nico ca lui causait probleme alors il m'a proposé de commenter ces lignes et qu'il allait se charger d'implémenter qqch de mieux

2023-10-18 12:59 UTC, Sari27 approved these changes

2023-10-18 13:02 UTC, merged